# Generated by Django 4.2.1 on 2023-07-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrionOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyid', models.IntegerField()),
                ('taxyear', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('percentownership', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('primaryowner', models.TextField()),
                ('interesttype', models.CharField(blank=True, max_length=60, null=True)),
                ('timestampchange', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orion_owner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionPartyaddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyaddrid', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('defaultaddress', models.TextField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=64, null=True)),
                ('address2', models.CharField(blank=True, max_length=64, null=True)),
                ('address3', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'orion_partyaddr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionPartyname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partynameid', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('defaultname', models.TextField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=167, null=True)),
                ('nametype', models.IntegerField(blank=True, null=True)),
                ('nametype_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'orion_partyname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geocode', models.CharField(blank=True, max_length=60, null=True)),
                ('addr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_predirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=64, null=True)),
                ('addr_roadsuffix', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_postdirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_state', models.CharField(blank=True, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('addr_unitnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_unittype', models.CharField(blank=True, max_length=5, null=True)),
                ('proptype', models.CharField(blank=True, max_length=60, null=True)),
                ('totmarket_acres', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True)),
                ('propcategory', models.CharField(blank=True, max_length=5, null=True)),
                ('propsubcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('propsubcategory_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'ohdc_property',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_phone', models.CharField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owns', models.ManyToManyField(related_name='people_owners', to='ditchdb.property')),
            ],
            options={
                'db_table': 'people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owns', models.ManyToManyField(related_name='organization_owners', to='ditchdb.property')),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OhdcPartyname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultname', models.BooleanField(default=False)),
                ('fullname', models.CharField(blank=True, max_length=167, null=True)),
                ('nametype', models.IntegerField(blank=True, null=True)),
                ('nametype_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('partyid', models.ForeignKey(db_column='partyid', on_delete=django.db.models.deletion.CASCADE, related_name='partyname', to='ditchdb.party')),
            ],
            options={
                'db_table': 'ohdc_partyname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OhdcPartyaddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultaddress', models.BooleanField(default=False)),
                ('address1', models.CharField(blank=True, max_length=64, null=True)),
                ('address2', models.CharField(blank=True, max_length=64, null=True)),
                ('address3', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('partyid', models.ForeignKey(db_column='partyid', on_delete=django.db.models.deletion.CASCADE, related_name='partyaddr', to='ditchdb.party')),
            ],
            options={
                'db_table': 'ohdc_partyaddr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(blank=True, choices=[('new', 'New property added'), ('removed', 'Property was removed from orion database'), ('changed', 'Property details were changed in orion database'), ('ownership', 'Property ownership was changed in orion database')], default=None, max_length=255, null=True)),
                ('propertyid', models.ForeignKey(db_column='propertyid', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='ditchdb.property')),
            ],
            options={
                'db_table': 'changes_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocode', models.CharField(blank=True, max_length=60, null=True)),
                ('addr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_predirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=64, null=True)),
                ('addr_roadsuffix', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_postdirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_state', models.CharField(blank=True, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('addr_unitnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_unittype', models.CharField(blank=True, max_length=5, null=True)),
                ('proptype', models.CharField(blank=True, max_length=60, null=True)),
                ('totmarket_acres', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True)),
                ('propcategory', models.CharField(blank=True, max_length=5, null=True)),
                ('propsubcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('propsubcategory_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('taxyear', models.IntegerField()),
                ('indistrict', models.BooleanField(default=False)),
                ('property', models.ForeignKey(blank=True, db_column='propertyid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orion_property', to='ditchdb.property')),
            ],
            options={
                'db_table': 'orion_property',
                'managed': True,
                'indexes': [models.Index(fields=['taxyear', 'indistrict'], name='orion_prope_taxyear_988a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OhdcOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryowner', models.BooleanField(default=False)),
                ('partyid', models.ForeignKey(db_column='partyid', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ditchdb.party')),
                ('property', models.ForeignKey(db_column='propertyid', on_delete=django.db.models.deletion.CASCADE, related_name='ohdc_owners', to='ditchdb.property')),
            ],
            options={
                'db_table': 'ohdc_owner',
                'managed': True,
                'unique_together': {('property', 'partyid')},
            },
        ),
    ]
