# Generated by Django 4.2.1 on 2023-07-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orionpartyaddr',
            old_name='partyid',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='orionpartyname',
            old_name='partyid',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='partyid',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='partyaddr',
            old_name='partyid',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='partyname',
            old_name='partyid',
            new_name='party',
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('property', 'party')},
        ),
    ]
