# Generated by Django 4.2.1 on 2023-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orionproperty',
            name='lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
