# Generated by Django 4.2.1 on 2023-09-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0002_organization_owner_person_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
    ]
