# Generated by Django 4.2.1 on 2023-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0002_rename_partyid_orionpartyaddr_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionpartyaddr',
            name='defaultaddress',
            field=models.BooleanField(default=False),
        ),
    ]
