# Generated by Django 4.2.1 on 2023-09-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0003_remove_organization_owner_remove_person_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owns',
        ),
        migrations.RemoveField(
            model_name='person',
            name='owns',
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ditchdb.owner'),
        ),
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ditchdb.owner'),
        ),
    ]
