# Generated by Django 4.2.1 on 2023-08-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0004_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='billing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ditchdb.billing'),
        ),
    ]
