# Generated by Django 4.2.1 on 2023-09-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ditchdb', '0004_remove_organization_owns_remove_person_owns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'ditchdb'), ('model', 'person')), models.Q(('app_label', 'ditchdb'), ('model', 'organization')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='current_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=21),
        ),
    ]
