# Generated by Django 4.2.1 on 2023-08-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ditchdb', '0005_property_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'ditchdb'), ('model', 'people')), models.Q(('app_label', 'ditchdb'), ('model', 'organizations')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
