# Generated by Django 4.2.1 on 2023-10-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0006_remove_billing_content_type_remove_billing_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='properties',
            field=models.ManyToManyField(related_name='people', to='ditchdb.property'),
        ),
    ]
