# Generated by Django 4.2.1 on 2023-09-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ditchdb', '0007_remove_property_billing_billing_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'ditchdb'), ('model', 'people')), models.Q(('app_label', 'ditchdb'), ('model', 'organizations')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
