# Generated by Django 4.2.1 on 2023-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0007_person_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
