# Generated by Django 4.2.1 on 2023-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditchdb', '0008_alter_billing_content_type_alter_billing_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
