# Generated by Django 4.2.1 on 2023-09-08 10:35

from django.db import migrations, models
from django.db import connection


def populate_new_field(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE ohdc_property SET address = concat_ws(' ', addr_number, addr_predirectional, addr_street, addr_roadsuffix, addr_postdirectional, addr_unitnumber);"
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ditchdb", "0009_property_address"),
    ]

    operations = [
        migrations.RunPython(populate_new_field, backwards),
    ]
