version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - .:/workspace:cached

    working_dir: /workspace
    command: sleep infinity

    environment:
      DJANGO_DEV: true # DO NOT SET THIS IN PRODUCTION
      DEV_CONTAINER: true
      PYTHONPATH: /workspace/backend

    ports:
      - '5173:5173'
      - '8000:8000'
      - '6006:6006'

    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  import-orion:
    build:
      context: .
      dockerfile: ./docker/import-orion.Dockerfile
    restart: 'no'
    volumes:
      - ./:/workspace
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SQL_SERVER_PASSWORD}
      CURRENT_YEAR: 2022
    ports:
      - '1433:1433'
    depends_on:
      - db
    profiles:
      - etl
    working_dir: /workspace/etl
    command: ./import_orion_into_postgres.sh

  qgis:
    build:
      context: .
      dockerfile: ./docker/qgis.Dockerfile
    environment:
      PYTHONPATH: /workspace/backend
      DJANGO_SETTINGS_MODULE: settings
    restart: 'no'
    volumes:
      - ./:/workspace
    depends_on:
      - db
    profiles:
      - changes
    working_dir: /workspace/etl
    command: ./find_changes.sh

volumes:
  postgres-data:
  e2e-postgres-data:
