# Generated by Django 4.2.1 on 2023-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrionOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyid', models.IntegerField()),
                ('taxyear', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('percentownership', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('primaryowner', models.TextField()),
                ('interesttype', models.CharField(blank=True, max_length=60, null=True)),
                ('timestampchange', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orion_owner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionPartyaddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyaddrid', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('defaultaddress', models.TextField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=64, null=True)),
                ('address2', models.CharField(blank=True, max_length=64, null=True)),
                ('address3', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'orion_partyaddr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionPartyname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partynameid', models.IntegerField()),
                ('partyid', models.IntegerField()),
                ('defaultname', models.TextField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=167, null=True)),
                ('nametype', models.IntegerField(blank=True, null=True)),
                ('nametype_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'orion_partyname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyid', models.IntegerField()),
                ('geocode', models.CharField(blank=True, max_length=60, null=True)),
                ('addr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_predirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=64, null=True)),
                ('addr_roadsuffix', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_postdirectional', models.CharField(blank=True, max_length=5, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_state', models.CharField(blank=True, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('addr_unitnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_unittype', models.CharField(blank=True, max_length=5, null=True)),
                ('proptype', models.CharField(blank=True, max_length=60, null=True)),
                ('totmarket_acres', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True)),
                ('propcategory', models.CharField(blank=True, max_length=5, null=True)),
                ('propsubcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('propsubcategory_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('taxyear', models.IntegerField()),
                ('indistrict', models.BooleanField()),
            ],
            options={
                'db_table': 'orion_property',
                'managed': True,
            },
        ),
    ]
