# Generated by Django 4.2.1 on 2023-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtorion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionproperty',
            name='indistrict',
            field=models.BooleanField(default=False),
        ),
    ]
